---
title: "FungalPlates"
author: "Jessi Raubenolt"
date: "2025-10-16"
output: html_document
---
@. Setup/Summary
```{r setup, include=TRUE}
library(tidyverse)
library(ggplot2)
library(car)
library(lme4)
library(lmerTest)
library(emmeans)

fungi.temp<-read.table(file="C:/Users/jessi/OneDrive - The Ohio State University/Ambrosia 2024-2025/Fungi/FungalAnalysis.csv", header=TRUE, sep=",")

ggplot(fungi.temp, aes(x=Species, y=Temp.ave, fill=Area))+ 
  geom_boxplot()+
  geom_point(position = position_jitterdodge(), shape=21)+
  labs(x="Species",
       y="Average Temperature (°C)",
       fill="Area of Plate")+
  theme_minimal()+
  theme(axis.text=element_text(size=12))+theme(axis.title=element_text(size=13))
```

@. Checking Assumptions
```{r Assumptions}
fit_model <- lmer(Temp.ave ~ Area*Species + (1|Plate), data=fungi.temp)
summary(fit_model)

plot(fit_model)
qqnorm(residuals(fit_model))
ranef_plate <- ranef(fit_model)$Plate
qqnorm(ranef_plate$`(Intercept)`)
hist(ranef_plate$`(Intercept)`)
```

@. ANOVA + mixed effects
```{r Mixed Effects Model}
lmer_test <- lmer(Temp.ave~factor(Area)*factor(Species)+ (1|Plate), data=fungi.temp)
anova(lmer_test, type=3)
summary(lmer_test)

anova_emm<-emmeans(lmer_test, ~Area*Species)
pairs(anova_emm)
```